# Generated by Django 4.2 on 2023-04-08 04:22

from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Activity",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "title",
                    models.CharField(
                        blank=True, max_length=35, verbose_name="赛事名"
                    ),
                ),
                (
                    "introduction",
                    models.TextField(blank=True, verbose_name="赛事简介"),
                ),
                (
                    "information",
                    models.JSONField(default=list, verbose_name="官网和通知"),
                ),
                (
                    "logo",
                    models.ImageField(
                        blank=True,
                        null=True,
                        upload_to="activity\\logo",
                        verbose_name="赛事logo",
                    ),
                ),
                ("start_time", models.DateField(verbose_name="开始时间")),
                ("end_time", models.DateField(verbose_name="结束时间")),
                (
                    "time_node",
                    models.JSONField(default=list, verbose_name="时间节点"),
                ),
                (
                    "create_time",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="创建时间"
                    ),
                ),
                (
                    "update_time",
                    models.DateTimeField(auto_now=True, verbose_name="更新时间"),
                ),
            ],
            options={
                "verbose_name": "赛事",
                "verbose_name_plural": "赛事",
                "db_table": "zq_activity",
            },
        ),
    ]
