# Generated by Django 4.2 on 2023-05-16 15:35

from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Banner",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=40, verbose_name="标题")),
                (
                    "subtitle",
                    models.CharField(
                        default="", max_length=40, verbose_name="副标题"
                    ),
                ),
                (
                    "cover",
                    models.ImageField(
                        default="", upload_to="banner", verbose_name="封面"
                    ),
                ),
                (
                    "photo",
                    models.ImageField(
                        default="", upload_to="banner", verbose_name="图片"
                    ),
                ),
                ("content", models.TextField(default="", verbose_name="内容")),
                ("score", models.IntegerField(default=0, verbose_name="分数")),
            ],
            options={
                "verbose_name": "轮播图推荐",
                "verbose_name_plural": "轮播图推荐",
                "db_table": "zq_banner",
            },
        ),
    ]
