version: "3"

services:
  ### Redis container ##########################################
  redis:
    image: redis:7.0.11
    ports:
      - "6379:6379"

  ### Celery container ########################################
  meili:
    image: getmeili/meilisearch:v1.1.1
    ports:
      - "7700:7700"
