# Generated by Django 4.2 on 2023-04-17 02:25

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Message",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("content", models.TextField(verbose_name="内容")),
                (
                    "type",
                    models.IntegerField(
                        choices=[
                            (0, "未知"),
                            (1, "系统消息"),
                            (2, "赛事消息"),
                            (3, "聊天消息"),
                        ],
                        default=0,
                        verbose_name="类型",
                    ),
                ),
                ("read", models.BooleanField(default=False, verbose_name="已读")),
                ("create_time", models.DateTimeField(verbose_name="创建时间")),
                (
                    "receiver",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="received_messages",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="接收用户",
                    ),
                ),
                (
                    "sender",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="send_messages",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="发送用户",
                    ),
                ),
            ],
            options={
                "verbose_name": "消息",
                "verbose_name_plural": "消息",
                "db_table": "zq_message",
                "ordering": ["-create_time"],
            },
        ),
    ]
