# Generated by Django 4.2 on 2023-04-21 12:56

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("chat", "0002_alter_message_receiver_alter_message_sender"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="message",
            name="type",
        ),
        migrations.AlterField(
            model_name="message",
            name="content",
            field=models.JSONField(default=dict, verbose_name="消息内容"),
        ),
    ]
