# Generated by Django 4.2 on 2023-04-21 13:07

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("chat", "0004_message_type"),
    ]

    operations = [
        migrations.AlterField(
            model_name="message",
            name="id",
            field=models.UUIDField(
                primary_key=True, serialize=False, verbose_name="消息ID"
            ),
        ),
    ]
