# Generated by Django 4.2 on 2023-04-21 15:42

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("chat", "0005_alter_message_id"),
    ]

    operations = [
        migrations.RenameField(
            model_name="message",
            old_name="read",
            new_name="is_read",
        ),
    ]
