# Generated by Django 4.2 on 2023-04-24 07:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("chat", "0006_rename_read_message_is_read"),
    ]

    operations = [
        migrations.AlterField(
            model_name="message",
            name="content",
            field=models.TextField(verbose_name="消息内容"),
        ),
        migrations.AlterField(
            model_name="message",
            name="type",
            field=models.IntegerField(
                choices=[(-1, "未知"), (0, "聊天消息"), (1, "已读")],
                default=-1,
                verbose_name="消息类型",
            ),
        ),
    ]
