# Generated by Django 4.2.2 on 2023-06-10 15:52

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("chat", "0008_alter_message_type"),
    ]

    operations = [
        migrations.AlterField(
            model_name="message",
            name="type",
            field=models.IntegerField(
                choices=[
                    (0, "未知"),
                    (1, "聊天消息"),
                    (2, "已读回执"),
                    (3, "图片消息"),
                    (4, "模板消息"),
                ],
                default=0,
                verbose_name="消息类型",
            ),
        ),
    ]
