# Generated by Django 4.2 on 2023-04-10 13:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Role",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        blank=True, max_length=30, verbose_name="角色名"
                    ),
                ),
                ("level", models.IntegerField(default=0, verbose_name="级别")),
                (
                    "description",
                    models.TextField(blank=True, verbose_name="角色描述"),
                ),
                (
                    "parent",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="sub_roles",
                        to="roles.role",
                        verbose_name="父级角色",
                    ),
                ),
            ],
            options={
                "verbose_name": "角色",
                "verbose_name_plural": "角色",
                "db_table": "zq_role",
            },
        ),
    ]
