# Generated by Django 4.2 on 2023-04-24 05:21

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("roles", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="role",
            name="level",
        ),
    ]
