# Generated by Django 4.2 on 2023-04-10 13:12

from django.db import migrations, models
import django.db.models.deletion
import server.utils.models.users


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Team",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        blank=True, max_length=30, verbose_name="队伍名"
                    ),
                ),
                (
                    "introduction",
                    models.TextField(blank=True, verbose_name="队伍简介"),
                ),
                (
                    "teacher",
                    models.CharField(
                        blank=True, max_length=10, verbose_name="指导老师"
                    ),
                ),
                (
                    "contact",
                    models.JSONField(default=list, verbose_name="联系方式"),
                ),
            ],
            options={
                "verbose_name": "队伍",
                "verbose_name_plural": "队伍",
                "db_table": "zq_team",
            },
        ),
        migrations.CreateModel(
            name="TeamDemand",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "number",
                    models.IntegerField(blank=True, verbose_name="招募人数"),
                ),
                ("detail", models.TextField(blank=True, verbose_name="招募详情")),
            ],
            options={
                "verbose_name": "招募需求",
                "verbose_name_plural": "招募需求",
                "db_table": "zq_team_demand",
            },
        ),
        migrations.CreateModel(
            name="TeamMember",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "team",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="members",
                        to="teams.team",
                        verbose_name="队伍",
                    ),
                ),
            ],
            options={
                "verbose_name": "队伍成员",
                "verbose_name_plural": "队伍成员",
                "db_table": "zq_team_member",
            },
            bases=(
                models.Model,
                server.utils.models.users.CommonUserInformation,
            ),
        ),
    ]
