# Generated by Django 4.2 on 2023-04-11 02:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("academies", "0002_init_data"),
    ]

    operations = [
        migrations.CreateModel(
            name="Team",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        blank=True, max_length=30, verbose_name="队伍名"
                    ),
                ),
                (
                    "introduction",
                    models.TextField(blank=True, verbose_name="队伍简介"),
                ),
                (
                    "teacher",
                    models.CharField(
                        blank=True, max_length=10, verbose_name="指导老师"
                    ),
                ),
                (
                    "contact",
                    models.JSONField(default=list, verbose_name="联系方式"),
                ),
            ],
            options={
                "verbose_name": "队伍",
                "verbose_name_plural": "队伍",
                "db_table": "zq_team",
            },
        ),
        migrations.CreateModel(
            name="TeamDemand",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "number",
                    models.IntegerField(blank=True, verbose_name="招募人数"),
                ),
                ("detail", models.TextField(blank=True, verbose_name="招募详情")),
            ],
            options={
                "verbose_name": "招募需求",
                "verbose_name_plural": "招募需求",
                "db_table": "zq_team_demand",
            },
        ),
        migrations.CreateModel(
            name="TeamMember",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "nickname",
                    models.CharField(
                        blank=True, max_length=20, verbose_name="昵称"
                    ),
                ),
                (
                    "degree",
                    models.IntegerField(
                        choices=[(0, "未知"), (1, "学士"), (2, "硕士"), (3, "博士")],
                        default=0,
                        verbose_name="学历",
                    ),
                ),
                ("grade", models.IntegerField(default=0, verbose_name="年级")),
                (
                    "introduction",
                    models.TextField(blank=True, verbose_name="个人简介"),
                ),
                (
                    "experience",
                    models.JSONField(default=list, verbose_name="经历"),
                ),
                (
                    "academy",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="%(class)s_users",
                        to="academies.academy",
                        verbose_name="学院",
                    ),
                ),
                (
                    "team",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="members",
                        to="teams.team",
                        verbose_name="队伍",
                    ),
                ),
            ],
            options={
                "verbose_name": "队伍成员",
                "verbose_name_plural": "队伍成员",
                "db_table": "zq_team_member",
            },
        ),
    ]
