# Generated by Django 4.2 on 2023-04-11 02:31

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("teams", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("activities", "0001_initial"),
        ("roles", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="teammember",
            name="user",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="join_teams",
                to=settings.AUTH_USER_MODEL,
                verbose_name="用户",
            ),
        ),
        migrations.AddField(
            model_name="teamdemand",
            name="role",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="team_demands",
                to="roles.role",
                verbose_name="角色",
            ),
        ),
        migrations.AddField(
            model_name="teamdemand",
            name="team",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="demands",
                to="teams.team",
                verbose_name="招募需求",
            ),
        ),
        migrations.AddField(
            model_name="team",
            name="activity",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="teams",
                to="activities.activity",
                verbose_name="所属赛事",
            ),
        ),
        migrations.AddField(
            model_name="team",
            name="leader",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="leader_teams",
                to=settings.AUTH_USER_MODEL,
                verbose_name="队长",
            ),
        ),
    ]
