# Generated by Django 4.2 on 2023-04-11 03:56

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("teams", "0002_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="team",
            name="public",
            field=models.BooleanField(default=False, verbose_name="是否公开"),
        ),
    ]
