# Generated by Django 4.2 on 2023-04-11 12:18

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):
    dependencies = [
        ("teams", "0004_alter_team_activity"),
    ]

    operations = [
        migrations.AddField(
            model_name="team",
            name="create_time",
            field=models.DateTimeField(
                auto_now_add=True,
                default=django.utils.timezone.now,
                verbose_name="创建时间",
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="team",
            name="update_time",
            field=models.DateTimeField(auto_now=True, verbose_name="更新时间"),
        ),
    ]
