# Generated by Django 4.2 on 2023-04-24 05:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("roles", "0001_initial"),
        ("teams", "0005_team_create_time_team_update_time"),
    ]

    operations = [
        migrations.AddField(
            model_name="teammember",
            name="role",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="team_members",
                to="roles.role",
                verbose_name="角色",
            ),
        ),
    ]
