# Generated by Django 4.2 on 2023-04-08 04:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Academy",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("level", models.IntegerField(default=0, verbose_name="级别")),
                ("name", models.CharField(max_length=50, verbose_name="院系名称")),
                (
                    "parent",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="sub_academies",
                        to="academies.academy",
                        verbose_name="父级",
                    ),
                ),
            ],
            options={
                "verbose_name": "院系",
                "verbose_name_plural": "院系",
                "db_table": "zq_academy",
            },
        ),
    ]
