# Generated by Django 4.2 on 2023-04-08 04:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Feedback",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("content", models.TextField(blank=True, verbose_name="反馈内容")),
                (
                    "type",
                    models.IntegerField(
                        choices=[
                            (0, "未知"),
                            (1, "赛事添加"),
                            (2, "使用困难"),
                            (3, "信息错误"),
                            (4, "封禁反馈"),
                            (5, "其他"),
                        ],
                        default=0,
                        verbose_name="反馈类型",
                    ),
                ),
                (
                    "created_time",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="创建时间"
                    ),
                ),
                (
                    "updated_time",
                    models.DateTimeField(auto_now=True, verbose_name="更新时间"),
                ),
            ],
            options={
                "verbose_name": "反馈",
                "verbose_name_plural": "反馈",
                "db_table": "zq_feedback",
            },
        ),
        migrations.CreateModel(
            name="FeedbackFile",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "file",
                    models.FileField(
                        blank=True,
                        null=True,
                        upload_to="feedback/file/",
                        verbose_name="反馈文件",
                    ),
                ),
                (
                    "created_time",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="创建时间"
                    ),
                ),
                (
                    "feedback",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="files",
                        to="feedbacks.feedback",
                        verbose_name="反馈",
                    ),
                ),
            ],
            options={
                "verbose_name": "反馈文件",
                "verbose_name_plural": "反馈文件",
                "db_table": "zq_feedback_file",
            },
        ),
    ]
