# Generated by Django 4.2 on 2023-04-08 04:22

import django.contrib.auth.models
import django.contrib.auth.validators
from django.db import migrations, models
import server.utils.models.users


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("auth", "0012_alter_user_first_name_max_length"),
        ("teams", "0001_initial"),
        ("activities", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="User",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "username",
                    models.CharField(
                        max_length=150,
                        unique=True,
                        validators=[
                            django.contrib.auth.validators.UnicodeUsernameValidator()
                        ],
                        verbose_name="用户名",
                    ),
                ),
                (
                    "password",
                    models.CharField(max_length=128, verbose_name="密码"),
                ),
                (
                    "email",
                    models.EmailField(
                        blank=True, max_length=254, verbose_name="邮箱"
                    ),
                ),
                (
                    "is_staff",
                    models.BooleanField(default=False, verbose_name="工作人员"),
                ),
                (
                    "is_active",
                    models.BooleanField(default=True, verbose_name="是否激活"),
                ),
                (
                    "is_superuser",
                    models.BooleanField(default=False, verbose_name="超级用户"),
                ),
                (
                    "phone",
                    models.CharField(
                        default="", max_length=13, verbose_name="手机"
                    ),
                ),
                (
                    "create_time",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="创建时间"
                    ),
                ),
                (
                    "update_time",
                    models.DateTimeField(auto_now=True, verbose_name="更新时间"),
                ),
                (
                    "openid",
                    models.CharField(
                        max_length=64,
                        null=True,
                        unique=True,
                        verbose_name="微信openid",
                    ),
                ),
                (
                    "union_id",
                    models.UUIDField(
                        blank=True,
                        null=True,
                        unique=True,
                        verbose_name="自强union_id",
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        blank=True, max_length=15, verbose_name="姓名"
                    ),
                ),
                (
                    "avatar",
                    models.ImageField(
                        default="user\\avatar\\default.jpg",
                        upload_to="user\\avatar",
                        verbose_name="头像",
                    ),
                ),
                (
                    "contact",
                    models.JSONField(default=list, verbose_name="联系方式"),
                ),
                (
                    "student_id",
                    models.CharField(
                        blank=True, max_length=20, verbose_name="学号"
                    ),
                ),
                (
                    "groups",
                    models.ManyToManyField(
                        blank=True,
                        help_text="The groups this user belongs to. A user will get all permissions granted to each of their groups.",
                        related_name="user_set",
                        related_query_name="user",
                        to="auth.group",
                        verbose_name="groups",
                    ),
                ),
                (
                    "like_activity",
                    models.ManyToManyField(
                        blank=True,
                        related_name="users",
                        to="activities.activity",
                        verbose_name="收藏的活动",
                    ),
                ),
                (
                    "like_team",
                    models.ManyToManyField(
                        blank=True,
                        related_name="users",
                        to="teams.team",
                        verbose_name="收藏的队伍",
                    ),
                ),
                (
                    "user_permissions",
                    models.ManyToManyField(
                        blank=True,
                        help_text="Specific permissions for this user.",
                        related_name="user_set",
                        related_query_name="user",
                        to="auth.permission",
                        verbose_name="user permissions",
                    ),
                ),
            ],
            options={
                "verbose_name": "用户",
                "verbose_name_plural": "用户",
                "db_table": "zq_user",
            },
            bases=(
                models.Model,
                server.utils.models.users.CommonUserInformation,
            ),
            managers=[
                ("objects", django.contrib.auth.models.UserManager()),
            ],
        ),
    ]
